version: '3'
networks:
  localdev:
    driver: bridge

services:
  # Database
  postgres:
    image: postgres:15.3-alpine
    container_name: ${APP_NAME}_postgres
    restart: always
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    networks:
      - localdev

  # WebServer
  nginx:
    image: nginx:stable-alpine
    container_name: ${APP_NAME}_nginx
    ports:
      - ${SERVER_PORT}:80
    links:
      - php
      - postgres
    volumes:
      - ./nginx/server.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./app:/var/www/html
    depends_on:
      - php
      - postgres
    networks:
      - localdev
  
  # PHP
  php:
    build:
      context: ./php
      dockerfile: php.Dockerfile
    container_name: ${APP_NAME}_php
    volumes:
      - ./app:/var/www/html:delegated
    working_dir: /var/www/html
    env_file: .env
    restart: always
    ports:
      - 9000:9000
      - 5902:5902
    networks:
      - localdev

   # Composer
  composer:
    image: composer:latest
    container_name: ${APP_NAME}_composer
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html
    restart: 'no'
    networks:
      - localdev